import type { Metadata } from "next";
import Link from "next/link";
import { release } from "../../lib/releases";
export const metadata: Metadata = { title: "Release notes" };
export default function ReleaseNotes() {
  return <main id="main" className="wrap"><div className="guide-hero"><p className="eyebrow coral">AN HONEST LOOK AT THE BUILD</p><h1>A first look.<br /><em>A real workspace.</em></h1><p className="lede">What you can explore today—and what needs a separate setup.</p></div><div className="guide-layout"><nav className="guide-nav" aria-label="Release sections"><a href="#included">What is included</a><a href="#boundaries">What is not included</a><a href="#changes">What changed</a></nav><div className="prose">
    <section id="included"><span className="release-pill">Version {release.version} · desktop preview</span><h2>Included in the download.</h2><ul><li>The native workspace engine and web interface, packaged inside the desktop app.</li><li>Automatic first-launch setup with fictional contacts, volunteer applications, and schedules.</li><li>Local sample edits that persist after closing and reopening the app.</li><li>Contact editing, spreadsheet import review, export, and duplicate review.</li><li>Writing-assistance requests with a clear distinction between model output and limited fallback templates.</li><li>Optional connection to an existing hosted Project Hope workspace.</li></ul><p>Product images on this website show actual application screens with synthetic demonstration records. They do not represent a customer deployment or endorsement.</p></section>
    <section id="boundaries"><h2>Important boundaries.</h2><ul><li><strong>Preview, not a managed production service.</strong> No hosted charity account is created automatically.</li><li><strong>Unsigned installers.</strong> OS publisher warnings are expected; code signing and macOS notarization are not in place.</li><li><strong>Separate AI setup.</strong> Generative model weights and Ollama are not bundled. A compatible local installation is needed for model-generated results.</li><li><strong>Human review.</strong> AI-generated material may be wrong and must be reviewed.</li><li><strong>No live sending from the sample.</strong> Email, invitations, calls, and other external actions are blocked.</li><li><strong>No mobile-store release.</strong> iPhone and Android app-store downloads are not available here.</li><li><strong>Not every integration is configured.</strong> Real phone service, email delivery, shared hosting, and production recovery require operator setup.</li><li><strong>Licensing is pending.</strong> The preview is available to explore without a purchase. Do not infer an approved open-source licence or production reuse rights.</li></ul></section>
    <section id="changes"><h2>A simpler way in.</h2><p>Earlier desktop builds required a prepared workspace website address before they could do anything. Version {release.version} adds an included sample environment so a first-time visitor can install the app and explore without a server connection.</p><p>The welcome screen now explains the difference between a workspace address and an email. The sample is protected by a per-launch local access token, is limited to loopback access, and cannot perform external sending actions.</p><p>The new website adds direct on-site downloads, platform-specific installation instructions, checksums, the new Project Hope identity, and motion that can be paused.</p></section>
    <Link className="button" href="/#download">Find your download <span aria-hidden="true">↓</span></Link>
  </div></div></main>;
}
