# Generated by Django 5.2.16 on 2026-08-23 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("organization_name", models.CharField(max_length=200)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("country_or_region", models.CharField(blank=True, max_length=120)),
                (
                    "team_size",
                    models.CharField(
                        choices=[
                            ("1", "1 person"),
                            ("2-5", "2–5 people"),
                            ("6-20", "6–20 people"),
                            ("21-50", "21–50 people"),
                            ("51+", "51+ people"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "primary_need",
                    models.CharField(
                        choices=[
                            ("operations", "Operations in one place"),
                            ("volunteers", "Volunteer coordination"),
                            ("grants", "Grants and evidence"),
                            ("communications", "Safer communications"),
                            ("impact", "Impact and reporting"),
                            ("accessibility", "Accessibility and translation"),
                            ("other", "Something else"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "plan_interest",
                    models.CharField(
                        choices=[
                            ("community", "Community — self-hosted"),
                            ("founding_partner", "Founding Partner — managed support"),
                            ("network", "Partner Network — multiple charities"),
                        ],
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("consent_to_contact", models.BooleanField(default=False)),
                (
                    "privacy_version",
                    models.CharField(default="2026-08-23", max_length=20),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("linkedin", "LinkedIn"),
                            ("partner", "Partner"),
                            ("referral", "Referral"),
                            ("direct", "Direct"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=24,
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=120)),
                ("utm_medium", models.CharField(blank=True, max_length=120)),
                ("utm_campaign", models.CharField(blank=True, max_length=160)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("pilot", "Pilot active"),
                            ("converted", "Converted"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=24,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("submission_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
