# Generated by Django 5.2.16 on 2026-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_pilotapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilotapplication",
            name="verification_email_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pilotapplication",
            name="verification_email_last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pilotapplication",
            name="verification_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
