# Generated by Django 5.2.17 on 2026-08-23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0005_normalize_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("password_fingerprint", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_last_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("email_attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_deliveries",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="identity_reset_status_exp_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("user",),
                        name="unique_pending_password_reset_delivery",
                    )
                ],
            },
        )
    ]
