# Generated by Django 5.2.17 on 2026-08-23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0006_passwordresetdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="security_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="security_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="MultiFactorCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encrypted_secret", models.TextField()),
                ("recovery_code_hashes", models.JSONField(default=list)),
                ("recovery_key_id", models.CharField(blank=True, max_length=16)),
                ("last_used_counter", models.BigIntegerField(default=-1)),
                ("enabled_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_credential",
                        to="identity.user",
                    ),
                ),
            ],
            options={"ordering": ["user__email"]},
        ),
    ]
