import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Privacy & the preview" };
export default function Privacy() {
  return <main id="main" className="wrap"><div className="guide-hero"><p className="eyebrow coral">CLEAR BY DESIGN</p><h1>A little clarity<br /><em>about your data.</em></h1><p className="lede">This notice covers the public showcase website and the local desktop sample—not a separately hosted charity workspace.</p></div><div className="prose">
    <section><h2>This website.</h2><p>There is no signup form, advertising tracker, or analytics script on this showcase. The site stores only your optional motion preference in your browser’s local storage. Your operating system’s reduced-motion preference is respected.</p><p>The site and its download storage run on Vercel. Normal infrastructure logs can contain request information such as IP address, browser details, requested files, and timestamps. Those logs are subject to the hosting provider’s policies. No “zero logging” promise is made.</p><p>Clicking Download requests an installer from this site’s download path. No account or email address is required.</p></section>
    <section><h2>The desktop sample.</h2><p>The included sample uses fictional records and stores edits in your local application profile. Do not put real beneficiary, donor, or safeguarding data into this sample. Local sample data is not a configured encrypted production database or shared backup service.</p><p>Startup diagnostics are written locally to help diagnose failures. The sample’s automatic account is for local demonstration only and does not create an online identity. The app may check for software updates.</p><p>If compatible Ollama models are running on your computer, the sample’s AI gateway sends writing requests to that local model service. If you connect a separately hosted workspace, its operator controls the configured AI and other providers.</p></section>
    <section><h2>Your charity’s workspace.</h2><p>Before using a hosted workspace with real records, your charity must establish its own privacy notice, access permissions, retention rules, approved providers, backup policy, and contact for data requests. The public showcase does not act as your charity’s managed service operator.</p><p>Ask your organization’s coordinator where its workspace is hosted and which services receive information. Do not assume the preview’s local behavior describes every hosted deployment.</p></section>
    <section id="pilot"><h2>If a workspace offers a pilot application.</h2><p>This showcase does not collect pilot applications. A separately hosted Project Hope deployment can enable its own application form. Its operator is responsible for identifying a monitored privacy contact and its hosting and email providers before accepting applications.</p><p>That optional form collects a contact name, work email, charity name, team size, primary need, preferred service path, optional website and region, optional notes, consent, campaign/referral fields, confirmation status, application stage, and timestamps. Do not enter client, beneficiary, payment-card, health, or government-identifier information.</p><p>Application information is used to confirm the request, assess fit, communicate about the pilot, operate an agreed service, prevent abuse, and measure aggregate application progress. It is not sold or used to train AI models. An expiring email link confirms the applicant; duplicate submissions do not create additional applicants or overwrite the first submission.</p><p>Authorized deployment administrators can access applications. Hosting and transactional-email providers process data to operate the service. Default retention is 14 days for unverified applications, 90 days after the last update for declined applications, and 365 days after the last update for verified applications awaiting follow-up. Active relationships remain while needed and must then be moved to a time-limited status by the operator; backup expiry follows that deployment’s policy.</p><p>Participation is optional. Access, correction, export, deletion, and withdrawal-of-contact requests go to the privacy contact published by that deployment’s operator. Identity may need to be confirmed. This notice does not create a managed service or substitute for that operator’s responsibilities.</p></section>
    <section><h2>Questions.</h2><p>For this preview, see the <Link href="/guide">installation and sample guide</Link>. For a live charity workspace, contact that organization’s coordinator or hosting partner. Do not include sensitive records or credentials in a support message.</p></section>
  </div></main>;
}
