import type { Metadata } from "next";
import Link from "next/link";
import { displaySize, downloadPath, release } from "../../lib/releases";

export const metadata: Metadata = { title: "Getting started" };
export default function Guide() {
  return <main className="wrap" id="main">
    <div className="guide-hero"><p className="eyebrow coral">A LITTLE HELP, WHEN YOU NEED IT</p><h1>Make yourself<br /><em>at home.</em></h1><p className="lede">A plain-language guide to your first look at Project Hope. Start with the sample. Take your time. Nothing is sent to real people.</p></div>
    <div className="guide-layout">
      <nav className="guide-nav" aria-label="Guide sections"><a href="#install">Install the app</a><a href="#first-look">Your first look</a><a href="#ai">Writing assistance</a><a href="#team">Connect your charity</a><a href="#verify">Check your download</a><a href="#help">If something goes wrong</a></nav>
      <div className="prose">
        <section id="install"><h2>One download. A first look.</h2><p>Choose your computer on the <Link href="/#download">download page</Link>. Each button starts an installer download directly from this website.</p>
          <h3>Windows 10 or 11 · 64-bit</h3><ol><li>Open the downloaded <strong>Project-Hope-{release.version}-win-x64.exe</strong> file.</li><li>Follow the installer. It installs for your Windows account and adds Start-menu and desktop shortcuts.</li><li>Open <strong>Project Hope</strong>. The sample workspace prepares itself automatically.</li></ol>
          <h3>Mac · Apple silicon</h3><ol><li>Download the macOS disk image. This build is for M-series Macs, not Intel Macs.</li><li>Open the <strong>.dmg</strong> file and drag Project Hope to Applications.</li><li>Open Project Hope from Applications. If macOS blocks the unsigned app, check the safety note below and follow your device policy.</li></ol>
          <h3>Linux · x86-64</h3><p>Download the AppImage, open its file properties, and enable permission to run it as a program. Then open it. A Debian package is also offered for compatible distributions. System requirements and AppImage support vary by distribution.</p>
          <div className="notice"><p><strong>A note about preview software.</strong> These installers are not code-signed or notarized. Your operating system may flag an unverified publisher. Do not disable your antivirus or organization’s security controls. Verify the file and ask your device administrator if you are unsure.</p></div>
        </section>
        <section id="first-look"><h2>Your first look is already set up.</h2><p>The app includes its workspace engine, local storage, and fictional example records. You do not need to install a database, Docker, Python, or a server to explore it.</p><ol><li>Start with <strong>CRM</strong> to view sample contacts. Make a small change and save it.</li><li>Explore volunteer applications and schedules. All example people and organizations are fictional.</li><li>Try contact import or duplicate review using a fictional spreadsheet.</li><li>Close and reopen the app. Your sample edits remain on this computer.</li></ol><p>Use <strong>sample or invented information only</strong>. The local sample is not a configured production system for sensitive beneficiary records, real donor information, or shared team operations.</p><p>The sample cannot send email, make calls, invite real people, or submit applications. A separate connection is needed for your organization’s hosted workspace.</p></section>
        <section id="ai"><h2>Helpful words. Human review.</h2><p>The writing workspace supports email drafting, intent classification, translation, and plain-language transformations. The result is always a draft for you to review. There is no automatic send button.</p><p><strong>Generative AI is optional and not bundled.</strong> The sample can use a compatible <a href="https://ollama.com/download" target="_blank" rel="noreferrer">Ollama installation</a> on the same computer. A technically confident helper can prepare the supported models:</p><pre><code>ollama pull qwen3:4b{"\n"}ollama pull all-minilm:latest</code></pre><p>Leave Ollama running, then open the writing workspace and try a fictional prompt. Model downloads require additional storage, memory, and internet access; performance depends on your computer.</p><p>When the model service is unavailable, Project Hope offers limited, clearly labelled <strong>safety templates</strong>. These are not model-generated answers. In particular, a fallback template is not a completed translation. Check the result label before using any output.</p><div className="notice"><p>Check facts, tone, names, and translations yourself. Never use the assistant to make an eligibility, safeguarding, or funding decision about a person.</p></div></section>
        <section id="team"><h2>Ready for your own charity?</h2><p>The download does not create a managed online charity account. For a shared workspace, your organization needs a separately hosted Project Hope service and someone responsible for operating it.</p><h3>If your workspace is already prepared</h3><ol><li>Choose <strong>Connect my charity</strong> in the sample, or <strong>Project Hope → Switch workspace</strong> in the app menu.</li><li>Enter the <strong>website address</strong> supplied by your coordinator, for example <code>https://workspace.your-charity.org</code>. This is not an email address.</li><li>After connecting, sign in with the account your coordinator prepared.</li></ol><p>The example address above is illustrative, not a live Project Hope service. An email such as <code>demo@example.org</code> cannot be used as a workspace address.</p><h3>What your setup partner needs to prepare</h3><ul><li>A hosted workspace with HTTPS and the correct organization boundary.</li><li>Individual staff accounts, appropriate permissions, and two-step verification.</li><li>Backups and a tested recovery process.</li><li>Approved email, AI, or phone providers for any enabled integrations.</li><li>Privacy, retention, and support arrangements appropriate to your charity.</li></ul><p>Those services can have operating costs. The desktop preview does not include managed hosting, a service-level guarantee, or live telephone service.</p></section>
        <section id="verify"><h2>Check what you downloaded.</h2><p>A SHA-256 checksum helps confirm that a file matches the published installer. It is an integrity check, not proof of an independently verified publisher.</p><h3>Windows</h3><p>Open PowerShell in your Downloads folder and run:</p><pre><code>Get-FileHash .\Project-Hope-{release.version}-win-x64.exe -Algorithm SHA256</code></pre><h3>Mac or Linux</h3><p>In the folder containing the downloaded file, use <code>shasum -a 256</code> on macOS or <code>sha256sum</code> on Linux, followed by the exact installer filename.</p>
          {release.assets.some((asset) => asset.available) ? <><p>Compare the result with the matching checksum below. It must match exactly, ignoring letter case.</p>{release.assets.filter((asset) => asset.available).map((asset) => <div className="checksum" key={asset.file}><p><a href={downloadPath(asset.file)} download>{asset.file}</a> · {displaySize(asset.bytes)}</p><code>{asset.sha256}</code></div>)}</> : <p>Installer checksums will appear here after release verification is complete. Unverified builds are not offered as downloads.</p>}
        </section>
        <section id="help"><h2>A small snag?</h2><h3>The workspace will not open</h3><p>Close Project Hope completely, then reopen it. The first launch may take longer while the app prepares the sample. If startup still fails, download the current installer again and reinstall it. Do not delete your profile folder if you want to preserve sample edits.</p><h3>I entered my email and could not connect</h3><p>The connection screen needs a workspace website address, not an email. You can choose <strong>Open sample workspace</strong> without either. For a charity account, ask your coordinator for the workspace address.</p><h3>I see a safety template instead of an AI draft</h3><p>The model service or supported model is unavailable. The rest of the sample still works. Follow the <a href="#ai">optional AI guidance</a>, or continue exploring contacts and schedules.</p><h3>A download does not start</h3><p>Check your browser’s downloads panel and your device’s download policy. Confirm you have enough disk space, then retry the same button. The download does not need an account or a visit to another website.</p><h3>I need help with my charity’s live workspace</h3><p>Contact your organization’s Project Hope coordinator or hosting partner. This public showcase does not provide a managed support desk. Do not send passwords, beneficiary records, or access tokens in a support message.</p></section>
        <Link className="button" href="/#download">Back to downloads <span aria-hidden="true">↓</span></Link>
      </div>
    </div>
  </main>;
}
